spaccincphpbb_activitypub_activitypub_webfinger:
    path: /.well-known/webfinger
    defaults: { _controller: spaccincphpbb.activitypub.controller.activitypub:webfinger }

spaccincphpbb_activitypub_activitypub_nodeinfo_known:
    path: /.well-known/nodeinfo
    defaults: { _controller: spaccincphpbb.activitypub.controller.activitypub:nodeinfo_known }

spaccincphpbb_activitypub_activitypub_activitypub:
    path: /activitypub
    defaults: { _controller: spaccincphpbb.activitypub.controller.activitypub:activitypub }
