spaccinc_activitypub_activitypub_webfinger:
    path: /.well-known/webfinger
    defaults: { _controller: spaccinc.activitypub.controller.activitypub:webfinger }

spaccinc_activitypub_activitypub_nodeinfo_known:
    path: /.well-known/nodeinfo
    defaults: { _controller: spaccinc.activitypub.controller.activitypub:nodeinfo_known }

spaccinc_activitypub_activitypub_activitypub:
    path: /activitypub
    defaults: { _controller: spaccinc.activitypub.controller.activitypub:activitypub }

